### ISSUE TITLE
Place Autocomplete 401 error: The feature is not enabled

### ISSUE THREAD

**Issue by Joe-ChenZ** [mapbox/mapbox-search-android#139]
## Environment

- Search SDK Component (check at least one)
    - [X] Core Search SDK (`SearchEngine` class, and etc.)
    - [ ] Offline Search SDK (`OfflineSearchEngine` class, and etc.)
    - [ ] Address Autofill SDK
    - [X] Search UI SDK
- Android OS version: SDK32
- Devices affected: Pixel XL API 32
- Search SDK Version: 
com.mapbox.search:place-autocomplete:1.0.0-rc.1
- Included in project Maps SDK, Nav SDK versions if available:
com.mapbox.maps:android:10.11.1
com.mapbox.navigation:android:2.10.1
## Code examples

placeAutocomplete = PlaceAutocomplete.create(accessToken = getString(R.string.mapbox_access_token))
//        placeAutocmplete.
        queryEditText = findViewById(R.id.query_text)
        lifecycleScope.launchWhenCreated {
            val response = placeAutocomplete.suggestions(
                query = "Washington DC",
            )

            response.onValue { suggestions ->
                Log.i("SearchApiExample", "Place Autocomplete results: $suggestions")
            }.onError { e ->
                Log.i("SearchApiExample", "Place Autocomplete error", e)
            }
        }

## Observed behavior and steps
I followed the installation steps and this website:
https://docs.mapbox.com/android/search/examples/place-autocomplete-ui/
But apparently Autocomplete always generates this exception:
SearchRequestException(message='{"status_code":401,"error":"The feature is not enabled","version":"63:6196f108d7bac14af1d1b746893a65309aac5867","code":"eJwrLkrWTyzI1M9IzEvJSS0q1i9LzMlMSSxJ1Ssq1jUyswQAx5sLjA=="}', code=401, cause=null)

So I tried a simplified version of the autocomplete feature with this website: 
https://docs.mapbox.com/android/search/examples/place-autocomplete/ 

It generates the same SearchRequestException while my map and GPS work fine:
![Screenshot_1677551529](https://user-images.githubusercontent.com/76936236/221738736-3cca6e32-a369-4d5b-bb43-18ebc3f1d849.png)

Place Autocomplete error
                                                                                                    SearchRequestException(message='{"status_code":401,"error":"The feature is not enabled","version":"63:6196f108d7bac14af1d1b746893a65309aac5867","code":"eJwrLkrWTyzI1M9IzEvJSS0q1i9LzMlMSSxJ1Ssq1jUyswQAx5sLjA=="}', code=401, cause=null)
                                                                                                    	at com.mapbox.search.base.utils.extension.SearchResponseErrorKt.toPlatformHttpException(SearchResponseError.kt:12)
                                                                                                    	at com.mapbox.search.base.engine.TwoStepsRequestCallbackWrapper.run$lambda-7(TwoStepsRequestCallbackWrapper.kt:74)
                                                                                                    	at com.mapbox.search.base.engine.TwoStepsRequestCallbackWrapper.$r8$lambda$O8P2IEYmBlShaf3i-FSXgZSHENQ(Unknown Source:0)
                                                                                                    	at com.mapbox.search.base.engine.TwoStepsRequestCallbackWrapper$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:920)
2023

## Expected behavior
My app does not behave the same as the one shown in the video demo, for both of the sample codes:
https://docs.mapbox.com/android/search/examples/place-autocomplete/ 
and
https://docs.mapbox.com/android/search/examples/place-autocomplete-ui/

**Comment by DzmitryFomchyn** [comment]
Hey @Joe-ChenZ,
Unfortunately, [Place Autocomplete SDK](https://docs.mapbox.com/android/search/guides/place-autocomplete/) is in private preview. Customers need to discuss with [sales team](https://www.mapbox.com/contact/sales/) whether they can access SDKs in private preview.

Alternatively, you can use [SearchEngine](https://docs.mapbox.com/android/search/guides/search-engine/) to achieve results similar to what Place Autocomplete SDK produces. Note that in this case you'll have to specify [`Geocoding`](https://docs.mapbox.com/android/search/api/core/1.0.0-rc.1/sdk/com.mapbox.search/-api-type/-g-e-o-c-o-d-i-n-g/) [Api Type](https://docs.mapbox.com/android/search/guides/search-engine/#api-type) because this type is available publicly.

I'll close this issue. Feel free to reopen it if you have more questions.

**Comment by Joe-ChenZ** [comment]
When will it be released for public use?

**Comment by DzmitryFomchyn** [comment]
Unfortunately, we don't have an estimation yet. Once it'll be public, we'll update information on docs.mapbox.com.
