### ISSUE TITLE
Libray not working com.mapbox.navigation

### ISSUE THREAD

**Issue by desaibhavesh92** [mapbox/mapbox-search-android#5]
## Environment

- Android OS version:
- Devices affected:
- Search SDK Version: 1.0.0-beta.24
- Included in project Maps SDK, Nav SDK versions if available:
Navigation SDK : 2.1.1

## Code examples

`
implementation "com.mapbox.navigation:android:2.1.1"
implementation "com.mapbox.search:mapbox-search-android-ui:1.0.0-beta.24"
`

## Observed behavior and steps

2021-12-29 16:07:59.455 12256-12256/com.sfl.navigationsystem E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.sfl.navigationsystem, PID: 12256
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedEv" referenced by "/data/app/~~5nk1-hA9Bps7Tya4d_wTmg==/com.sfl.navigationsystem-XaTGAx2k2VmsrKVNyxtalg==/lib/arm64/libnavigator-android.so"...
        at android.app.ActivityThread.installProvider(ActivityThread.java:7285)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6821)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6716)
        at android.app.ActivityThread.access$1300(ActivityThread.java:238)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7698)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
     Caused by: androidx.startup.StartupException: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedEv" referenced by "/data/app/~~5nk1-hA9Bps7Tya4d_wTmg==/com.sfl.navigationsystem-XaTGAx2k2VmsrKVNyxtalg==/lib/arm64/libnavigator-android.so"...
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:162)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198)
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7280)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6821) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6716) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:238) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7698) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN6mapbox6common9Scheduler15CreateSequencedEv" referenced by "/data/app/~~5nk1-hA9Bps7Tya4d_wTmg==/com.sfl.navigationsystem-XaTGAx2k2VmsrKVNyxtalg==/lib/arm64/libnavigator-android.so"...
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.mapbox.common.loader.MapboxLibraryLoader.load(MapboxLibraryLoader.kt:19)
        at com.mapbox.navigator.MapboxNavigationNativeInitializer.create(MapboxNavigationNativeInitializer.kt:16)
        at com.mapbox.navigator.MapboxNavigationNativeInitializer.create(MapboxNavigationNativeInitializer.kt:10)
        at androidx.startup.AppInitializer.doInitialize(AppInitializer.java:155)
        at androidx.startup.AppInitializer.discoverAndInitialize(AppInitializer.java:198) 
        at androidx.startup.InitializationProvider.onCreate(InitializationProvider.java:38) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2388) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2358) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7280) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6821) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6716) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:238) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1914) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7698) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952) 

## Expected behavior

Should work with navigation SDK

**Comment by DzmitryFomchyn** [comment]
Hey @desaibhavesh92, Search SDK [v`1.0.0-beta.24`](https://github.com/mapbox/mapbox-search-android/releases/tag/v1.0.0-beta.24) and Nav SDK v`2.1.1` are incompatible as they use different versions of the Common SDK, try please Nav SDK [2.2.0-beta.1](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.2.0-beta.1).

**Comment by shikoko** [comment]
> Hey @desaibhavesh92, Search SDK [v`1.0.0-beta.24`](https://github.com/mapbox/mapbox-search-android/releases/tag/v1.0.0-beta.24) and Nav SDK v`2.1.1` are incompatible as they use different versions of the Common SDK, try please Nav SDK [2.2.0-beta.1](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.2.0-beta.1).

What version is then compatible with Nav SDK 2.1.1? Because using another beta version is too risky for us right now.

Also, are you still relying on jcenter/bintray because I can't run the project anymore, I'm getting this all the time:
> Could not HEAD 'https://mapbox.bintray.com/mapbox/com/mapbox/search/mapbox-search-android/1.0.0-beta.24/mapbox-search-android-1.0.0-beta.24.pom'. Received status code 502 from server: Bad Gateway

**Comment by desaibhavesh92** [comment]
Thanks @DzmitryFomchyn for your response. I degrade Search SDK to **v1.0.0-beta.23** and its working with NAV SDK [v2.1.1](https://github.com/mapbox/mapbox-navigation-android/releases/tag/v2.1.1)

@shikoko You can use  Search SDK **v1.0.0-beta.23**
