### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.maps.assets.AssetManagerProvider.initialize(android.content.res.AssetManager) (tried Java_com_mapbox_maps_assets_AssetManagerProvider_initialize and Java_com_mapbox_maps_assets_AssetManagerProvider_initialize__Landroid_content_res_AssetManager_2)

### ISSUE THREAD

**Issue by cattcal** [mapbox/mapbox-search-android#69]
## Environment

- Android OS version: 12 
- Devices affected: XiaoMi
- Search SDK Version: 1.0.0-beta.35
- Included in project Maps SDK, Nav SDK versions if available:  Maps SDK：10.7.0

## Observed behavior and steps

 Unable to start activity ComponentInfo{com.xxx.xxx.debug/comxxx.xxx.module.growthmonitor.activity.MapBoxGrowthMonitorActivity}: android.view.InflateException: Binary XML file line #17 in com.xxx.xxx.debug:layout/mapbox_growth_monitor_activity: Binary XML file line #17 in com.xxx.xxx.debug:layout/mapbox_growth_monitor_activity: Error inflating class com.mapbox.maps.MapView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3790)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3957)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:106)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2335)

**Comment by cattcal** [comment]
Version compatibility issue has been resolved
